extern const GeoLayout testing_area_1_geo[];
extern const GeoLayout testing_area_1[];
extern const Collision testing_area_1_collision[];
extern const MacroObject testing_area_1_macro_objs[];
extern u8 testing_dl_chk_i8[];
extern Vtx testing_dl_Plane_mesh_layer_1_vtx_cull[8];
extern Vtx testing_dl_Plane_mesh_layer_1_vtx_0[4];
extern Gfx testing_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx testing_dl_Plane_001_mesh_layer_1_vtx_cull[8];
extern Vtx testing_dl_Plane_001_mesh_layer_1_vtx_0[4];
extern Gfx testing_dl_Plane_001_mesh_layer_1_tri_0[];
extern Vtx testing_dl_Plane_002_mesh_layer_1_vtx_cull[8];
extern Vtx testing_dl_Plane_002_mesh_layer_1_vtx_0[4];
extern Gfx testing_dl_Plane_002_mesh_layer_1_tri_0[];
extern Vtx testing_dl_Plane_003_mesh_layer_1_vtx_cull[8];
extern Vtx testing_dl_Plane_003_mesh_layer_1_vtx_0[4];
extern Gfx testing_dl_Plane_003_mesh_layer_1_tri_0[];
extern Vtx testing_dl_Plane_004_mesh_layer_1_vtx_cull[8];
extern Vtx testing_dl_Plane_004_mesh_layer_1_vtx_0[4];
extern Gfx testing_dl_Plane_004_mesh_layer_1_tri_0[];
extern Gfx mat_testing_dl_f3dlite_material[];
extern Gfx mat_revert_testing_dl_f3dlite_material[];
extern Gfx mat_testing_dl_f3dlite_material_001[];
extern Gfx mat_revert_testing_dl_f3dlite_material_001[];
extern Gfx mat_testing_dl_f3dlite_material_003[];
extern Gfx mat_revert_testing_dl_f3dlite_material_003[];
extern Gfx testing_dl_Plane_mesh_layer_1[];
extern Gfx testing_dl_Plane_001_mesh_layer_1[];
extern Gfx testing_dl_Plane_002_mesh_layer_1[];
extern Gfx testing_dl_Plane_003_mesh_layer_1[];
extern Gfx testing_dl_Plane_004_mesh_layer_1[];
